<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LP-CND5160BZR" ignored="0" name="srcFolder Classes" tests="23" failures="2" timestamp="04 Oct 2018 02:12:08 GMT" time="244.228" errors="0">
  <testcase name="test1" time="0.012" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test1" time="0.003" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test1" time="0.004" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test1" time="0.004" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test1" time="0.002" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test3" time="0.001" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="testGmilLink" time="0.004" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="testLogo" time="0.14" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="test2" time="0.002" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="testTitle" time="0.024" classname="com.testng.tests.DependsOnMethodsTest"/>
  <testcase name="infiniteLoop" time="0.013" classname="com.testng.tests.InfiniteLoopTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.tests.InfiniteLoopTest.infiniteLoop() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.tests.InfiniteLoopTest.infiniteLoop() didn't finish within the time-out 2
	at sun.nio.cs.SingleByte$Encoder.encodeLoop(SingleByte.java:219)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:271)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.PrintStream.newLine(PrintStream.java:545)
	at java.io.PrintStream.println(PrintStream.java:807)
	at com.testng.tests.InfiniteLoopTest.infiniteLoop(InfiniteLoopTest.java:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- infiniteLoop -->
  <testcase name="numberFormat" time="0.008" classname="com.testng.tests.InfiniteLoopTest"/>
  <testcase name="invocationCountTest" time="0.004" classname="com.testng.tests.InvocationCountTest"/>
  <testcase name="invocationCountTest" time="0.008" classname="com.testng.tests.InvocationCountTest"/>
  <testcase name="invocationCountTest" time="0.0" classname="com.testng.tests.InvocationCountTest"/>
  <testcase name="invocationCountTest" time="0.0" classname="com.testng.tests.InvocationCountTest"/>
  <testcase name="invocationCountTest" time="0.016" classname="com.testng.tests.InvocationCountTest"/>
  <testcase name="realTest" time="0.0" classname="com.testng.tests.KhadarTest"/>
  <testcase name="testGmilLink" time="0.004" classname="com.testng.tests.LaxmanTest"/>
  <testcase name="testTitle" time="0.048" classname="com.testng.tests.LaxmanTest"/>
  <testcase name="testLogo" time="0.113" classname="com.testng.tests.LaxmanTest"/>
  <testcase name="test3" time="0.004" classname="com.testng.tests.LaxmanTest">
    <failure type="java.lang.AssertionError" message="Test FAIL..">
      <![CDATA[java.lang.AssertionError: Test FAIL..
	at com.testng.tests.LaxmanTest.test3(LaxmanTest.java:52)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.095" classname="com.testng.tests.LaxmanTest"/>
</testsuite> <!-- srcFolder Classes -->
